library(ahp)
ahpFile <- system.file("extdata/custom", "ipady4.ahp", package="ahp")
ipady4ahp <- Load(ahpFile)
Calculate(ipady4ahp)
print(ipady4ahp, priority = function(x) x$sparent$priority["total", x$name])
Visualize(ipady4ahp)
Analyze(ipady4ahp)
AnalyzeTable(ipady4ahp)
AnalyzeTable(ipady4ahp, decisionMaker = "Father")
AnalyzeTable(ipady4ahp, decisionMaker = "Mother")
AnalyzeTable(ipady4ahp, decisionMaker = "Child")